image: node:5-onbuild

before_script:
  - node -v
  - npm -v
  - npm install -g gulp
  - npm install

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - gulp build
  only:
    - master
  tags:
    - docker
    - node

test_job:
  stage: test
  script:
    - npm test
  only:
    - master
  tags:
    - docker
    - node
